export const USER_ALL_SESSION = "USER_ALL_SESSION";
export const USER_All_SESSION_SUCCESS = "USER_All_SESSION_SUCCESS";
export const USER_All_SESSION_FAILURE = "USER_All_SESSION_FAILURE";

export const ADVANCE_FEATURE = "ADVANCE_FEATURE";
export const ADVANCE_FEATURE_SUCCESS = "ADVANCE_FEATURE_SUCCESS";
export const ADVANCE_FEATURE_FAILURE = "ADVANCE_FEATURE_FAILURE";

export const USER_OUESTION_SESSION = "USER_OUESTION_SESSION";
export const USER_SESSION_HISTORY = "USER_SESSION_HISTORY";

export const USER_ALL_SESSION_LIVE = "USER_ALL_SESSION_LIVE";
export const GET_USER_All_SESSION_SUCCESS_LIVE =
  "GET_USER_All_SESSION_SUCCESS_LIVE";

export const GET_USER_All_SESSION_FAILURE_LIVE =
  "GET_USER_All_SESSION_FAILURE_LIVE";
