export const SAVE_WHATSAPPINT = "SAVE_WHATSAPPINT";
export const SAVE_WHATSAPPINT_SUCCESS = "SAVE_WHATSAPPINT_SUCCESS";
export const SAVE_WHATSAPPINT_FAILURE = "SAVE_WHATSAPPINT_FAILURE";

export const UPDATE_WHATSAPP_REQUEST = "UPDATE_WHATSAPP_REQUEST";
export const UPDATE_WHATSAPP_SUCCESS = "UPDATE_WHATSAPP_SUCCESS";
export const UPDATE_WHATSAPP_FAILURE = "UPDATE_WHATSAPP_FAILURE";

export const DELETE_WHATSAPP_REQUEST = "DELETE_WHATSAPP_REQUEST";
export const DELETE_WHATSAPP_SUCCESS = "DELETE_WHATSAPP_SUCCESS";
export const DELETE_WHATSAPP_FAILURE = "DELETE_WHATSAPP_FAILURE";


export const GET_WHATSAPP_REQUEST = "GET_WHATSAPP_REQUEST";
export const GET_WHATSAPP_SUCCESS = "GET_WHATSAPP_SUCCESS";
export const GET_WHATSAPP_FAILURE = "GET_WHATSAPP_FAILURE";