export const FETCH_SHOPIFY_DASHBOARD_REQUEST = "FETCH_SHOPIFY_DASHBOARD_REQUEST";
export const FETCH_SHOPIFY_DASHBOARD_SUCCESS = "FETCH_SHOPIFY_DASHBOARD_SUCCESS";
export const FETCH_SHOPIFY_DASHBOARD_FAILURE = "FETCH_SHOPIFY_DASHBOARD_FAILURE";