//Auth actions
export const GET_SUBSCRIPTION_DATA = "GET_SUBSCRIPTION_DATA";
export const GET_SUBSCRIPTION_DATA_SUCCESS = "GET_SUBSCRIPTION_DATA_SUCCESS";
export const GET_SUBSCRIPTION_DATA_FAILURE = "GET_SUBSCRIPTION_DATA_FAILURE";
