//Auth actions
export const GET_SUBSCRIPTION_DATA = "GET_SUBSCRIPTION_DATA";
export const GET_SUBSCRIPTION_DATA_SUCCESS = "GET_SUBSCRIPTION_DATA_SUCCESS";
export const GET_SUBSCRIPTION_DATA_FAILURE = "GET_SUBSCRIPTION_DATA_FAILURE";
export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_REQUEST_SUCCESS = "CREATE_PAYMENT_REQUEST_SUCCESS";
export const CREATE_PAYMENT_REQUEST_FAILURE = "CREATE_PAYMENT_REQUEST_FAILURE";
export const DB_ENTRY_SUBSCRIPTION = "DB_ENTRY_SUBSCRIPTION";
export const DB_ENTRY_SUBSCRIPTION_SUCCESS = "DB_ENTRY_SUBSCRIPTION_SUCCESS";
export const DB_ENTRY_SUBSCRIPTION_FAILURE = "DB_ENTRY_SUBSCRIPTION_FAILURE";
export const RESET_SPECIFIC_STATE = "RESET_SPECIFIC_STATE";
