export const CREATE_WHATSAPP_CAMPAIGN = 'CREATE_WHATSAPP_CAMPAIGN';
export const CREATE_WHATSAPP_CAMPAIGN_SUCCESS = 'CREATE_WHATSAPP_CAMPAIGN_SUCCESS';
export const CREATE_WHATSAPP_CAMPAIGN_FAILURE = 'CREATE_WHATSAPP_CAMPAIGN_FAILURE';

export const FETCH_WHATSAPP_TEMPLATES = 'FETCH_WHATSAPP_TEMPLATES';
export const FETCH_WHATSAPP_TEMPLATES_SUCCESS = 'FETCH_WHATSAPP_TEMPLATES_SUCCESS';
export const FETCH_WHATSAPP_TEMPLATES_FAILURE = 'FETCH_WHATSAPP_TEMPLATES_FAILURE';

export const CREATE_WHATSAPP_TEMPLATE = 'CREATE_WHATSAPP_TEMPLATE';
export const CREATE_WHATSAPP_TEMPLATE_SUCCESS = 'CREATE_WHATSAPP_TEMPLATE_SUCCESS';
export const CREATE_WHATSAPP_TEMPLATE_FAILURE = 'CREATE_WHATSAPP_TEMPLATE_FAILURE';

export const FETCH_WHATSAPP_CAMPAIGNS = 'FETCH_WHATSAPP_CAMPAIGNS';
export const FETCH_WHATSAPP_CAMPAIGNS_SUCCESS = 'FETCH_WHATSAPP_CAMPAIGNS_SUCCESS';
export const FETCH_WHATSAPP_CAMPAIGNS_FAILURE = 'FETCH_WHATSAPP_CAMPAIGNS_FAILURE';
