export const CREATE_WHATSAPP_CAMPAIGN = 'CREATE_WHATSAPP_CAMPAIGN';
export const CREATE_WHATSAPP_CAMPAIGN_SUCCESS = 'CREATE_WHATSAPP_CAMPAIGN_SUCCESS';
export const CREATE_WHATSAPP_CAMPAIGN_FAILURE = 'CREATE_WHATSAPP_CAMPAIGN_FAILURE';
