export const FETCH_WHATSAPP_DASHBOARD_REQUEST = "FETCH_WHATSAPP_DASHBOARD_REQUEST";
export const FETCH_WHATSAPP_DASHBOARD_SUCCESS = "FETCH_WHATSAPP_DASHBOARD_SUCCESS";
export const FETCH_WHATSAPP_DASHBOARD_FAILURE = "FETCH_WHATSAPP_DASHBOARD_FAILURE";