export const FETCH_WHATSAPP_DASHBOARD_REQUEST = "FETCH_WHATSAPP_DASHBOARD_REQUEST";
export const FETCH_WHATSAPP_DASHBOARD_SUCCESS = "FETCH_WHATSAPP_DASHBOARD_SUCCESS";
export const FETCH_WHATSAPP_DASHBOARD_FAILURE = "FETCH_WHATSAPP_DASHBOARD_FAILURE";

export const FETCH_WHATSAPP_MESSAGES_REQUEST = "FETCH_WHATSAPP_MESSAGES_REQUEST";
export const FETCH_WHATSAPP_MESSAGES_SUCCESS = "FETCH_WHATSAPP_MESSAGES_SUCCESS";
export const FETCH_WHATSAPP_MESSAGES_FAILURE = "FETCH_WHATSAPP_MESSAGES_FAILURE";